### ISSUE TITLE
Pipe into ffmpeg

### ISSUE THREAD

**Issue by DavidVentura** [Robert904/mumblerecbot#1]
Hi, I'd like to pipe the audio of everyone in the channel to ffmpeg. Is this possible with mumblerecbot? 
Cheers

**Comment by Robert904** [comment]
Hello,

That's actually what I'm doing (not with ffmpeg but with oggenc2).

In the file "constant.py", there is a line "ENCODER = ..." which give a commandline to pipe the audio stream to...  if this commandline fails, the application fallback to standard wav.

Of course in this case this is raw 16bits-2channels-48Khz audio that is sent, not wav format...

The line
CHANNEL = "" # channel to move in ("" = root)
indicate in which channel name the application will try to move in.  It will record any audio he is allowed to ear (based on the mumble channels configurations)

Robert
