### ISSUE TITLE
"sound_add module not found"

### ISSUE THREAD

**Issue by DavidVentura** [Robert904/mumblerecbot#4]
Hi, this has been working almost perfectly for about 2 months and today when people <spoke> on mumble, the bot crashed telling me it couldn't found the module "sound_add".
This is weird.
What can I do to fix it? It is not working atm, I didn't update anything

**Comment by Robert904** [comment]
That is indeed weird...  sound_add is a small cython module to add 2 audio without clipping, that I wrote in cython for performance reasons...  there should be a file named "sound_add.so" in the root directory of the installation that is created by building what's in "mumblerecbotfast"...

Could it have been deleted ?

**Comment by DavidVentura** [comment]
I didn't change anything. Now it works. It screwed me up on monday, but I went back to the old method (recording from another pc connected to mumble with pulse recording from monitor). I'll check if this happens again..

**Comment by Robert904** [comment]
Difficult to help you without more information...
Honestly, finding a module or a file is a pure python matter, not related to my code...  Something must have happen like a change in the path environment or an automatic update of something by debian...

**Comment by DavidVentura** [comment]
it happened again, this time when I added another user to the mumble server.. I'm convinced this is some kind of sorcery. nothing that can't be fixed with rebuilding.

**Comment by saerdnaer** [comment]
you have to run make in the mumblerecbotfast folder. The error happens every time when two users or more are speaking at the same time
